on: [push]

jobs:
  sigma_code_scanning_run_steps:
    runs-on: ubuntu-latest
    container:
      image: appsechala/sigmatesting:latest
      credentials:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.DOCKPASS }}
      options: --user 1001:1001  # Adjust the user ID and group ID as needed
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Sigma analysis
        run: sigma analyze --format github .
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sigma-results.json
